env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
         "import/prefer-default-export":"off",
         "react/jsx-filename-extension": [ 1, { "extensions": [ ".js", ".jsx" ] } ],
         no-console: 2,
         no-param-reassign: 0,
         react/jsx-props-no-spreading: off,
}
